frontend.url: https://localhost:4202

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    healthcheck:
      enabled: true
    lease:
      duration: 5
  instance:
    hostName: localhost
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
    statusPageUrl: https://${eureka.instance.hostname}:${eureka.instance.securePort}/info
    healthCheckUrl: https://${eureka.instance.hostName}:${eureka.instance.securePort}/health
    homePageUrl: https://${eureka.instance.hostname}:${eureka.instance.securePort}/
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    preferIpAddress: true



server:
  #servlet:
    #context-path: /api
  port: 8085
  ssl:
    key-store: classpath:stores/keystore.p12
    key-store-password: pass147
    key-store-type: PKCS12
    key-alias: paypal_microservice
    # trust-store: classpath:stores/truststore.p12
    # trust-store-password: pass456
    # trust-store-type: PKCS12
    protocol: TLS
    enabled-protocols: TLSv1.2
    ciphers: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    # Za definisanje ovoga, treba prethodno iskoristi kod u PkiApplication klasi, koja izlistava sve podrzane
    # chipers u Javi instaliranoj na nasem racunaru
    # Kod je pronadjen na: https://stackoverflow.com/questions/48934210/java-ssl-error-cannot-support-tls-ecdhe-rsa-with-aes-256-gcm-sha384
    client-auth: want
    # for two way authentication, use value: need





spring:
  application:
    name: pt_paypal-microservice # stavljamo prefiks "pt_" (pt = payment type) da bismo znali razlikovati mikroservise
                                  # koji se odnose na tipove placanja od ostalih mikorservisa