server:
  port: 8762
  ssl:
    key-store: classpath:stores/keystore.jks
    key-store-password: key_store_pass
    key-store-type: JKS
    key-alias: proxy_server
    trust-store: classpath:stores/truststore.jks
    trust-store-password: trust_store_pass
    trust-store-type: JKS
    protocol: TLS
    enabled-protocols: TLSv1.2
    ciphers: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    # Za definisanje ovoga, treba prethodno iskoristi kod u PkiApplication klasi, koja izlistava sve podrzane
    # chipers u Javi instaliranoj na nasem racunaru
    # Kod je pronadjen na: https://stackoverflow.com/questions/48934210/java-ssl-error-cannot-support-tls-ecdhe-rsa-with-aes-256-gcm-sha384
    client-auth: want
    # for two way authentication, use value: need
  
spring:
  application:
    name: proxy-server

eureka:
  client:
    registerWithEureka: false #true
    fetchRegistry: true
    #service-url:
    serviceUrl:
      defaultZone: https://localhost:8761/eureka/

  instance:
    hostname: localhost
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
    preferIpAddress: true
    

zuul:
  host:
    connect-timeout-millis: 100000
    socket-timeout-millis: 100000
  retryable: true
  routes.discovery:
     path: /discovery/**
     url: https://localhost:8761
  sslHostnameValidationEnabled: false

#hystrix:
#  command:
#    default:
#      execution:
#        timeout:
#          enabled: false
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 500000
hystrix.command.gateway.execution.isolation.thread.timeoutInMilliseconds: 500000


ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000
  IsSecure: true
  # Jovo: dok nisam dodao "IsSecure: true", nije bilo moguce poslati request od payment microservice-a
  # do bitcoin microservice preko proxy server-a (stalno je vracao Bad Request, 400)